# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbffile',
            old_name='file1',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='dbffile',
            name='file2',
        ),
        migrations.AddField(
            model_name='dbffile',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
